### ISSUE TITLE
Help with this integration error, please!

### ISSUE THREAD

**Issue by whiliam** [andersevenrud/ha-nexa-bridge-x#28]
This error originated from a custom integration.

Logger: custom_components.nexa_bridge_x.nexa
Source: custom_components/nexa_bridge_x/nexa.py:476
Integration: Nexa Bridge X (documentation, issues)
First occurred: 2:49:06 AM (2 occurrences)
Last logged: 2:54:04 AM

Unexpected error fetching Nexa Bridge X Coordinator data: 'name'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/nexa_bridge_x/nexa.py", line 665, in _async_update_data
    list(map(lambda n: NexaNode(n, self.legacy), nodes)),
  File "/config/custom_components/nexa_bridge_x/nexa.py", line 665, in <lambda>
    list(map(lambda n: NexaNode(n, self.legacy), nodes)),
  File "/config/custom_components/nexa_bridge_x/nexa.py", line 476, in __init__
    self.name = node["name"]
KeyError: 'name'

**Comment by whiliam** [comment]
Alright.
Hmm, yes it works perfectly connecting to nexa via postman.

**Comment by andersevenrud** [comment]
Could you attach the output from these two endpoints here (and censor any personal identifiers) ?

**Comment by whiliam** [comment]
Sure thing, here you go!
[info.txt](https://github.com/andersevenrud/ha-nexa-bridge-x/files/11657738/info.txt)
[nodes.txt](https://github.com/andersevenrud/ha-nexa-bridge-x/files/11657739/nodes.txt)

**Comment by andersevenrud** [comment]
Thanks! That gave me the information I needed to track down why this occurred, and a fix is incoming!

**Comment by andersevenrud** [comment]
New release out now!

**Comment by andersevenrud** [comment]
Just to leave a record of what exactly happened here.

---

For some reason a `node` returned from the `/nodes` endpoint did not contain a `name` property.

Their documentation [^1] indicates that this will always be present, so the the parsing section of this data in this integration assumed this is always the case.

[^1]: https://nexa.se/docs/#api-nodes-getNodes

**Comment by andersevenrud** [comment]
FYI, I just went over the data you attached again and noticed that your bridge responded with some values that is not documented.

I added them in and released a new version. So you should get some additional information on some of your devices, like your "move" sensor should now get a proper value.
