### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'type'

### ISSUE THREAD

**Issue by maxfrippe** [andersevenrud/ha-nexa-bridge-x#29]
Hello
When I run on a raspberry Pi with debian 11 and python 3.9 I get the error
TypeError: unsupported operand type(s) for |: 'type' and 'type' in nexa.py

I replaced this line
NexaNodeValueType = str | int | float | bool
with this line
NexaNodeValueType = Union[str, int, float, bool]

and got it working
Not sure if the line below was also needed.
from typing import cast, Union, Any

**Comment by maxfrippe** [comment]
As Brian Kernighan wrote  " "Once I figure out how ... I will try to submit a pull request. "
https://arstechnica.com/gadgets/2022/08/unix-legend-who-owes-us-nothing-keeps-fixing-foundational-awk-code/

is there alternative way?

**Comment by andersevenrud** [comment]
No worries. I can patch this a little bit later today.

**Comment by andersevenrud** [comment]
New version is published.

Thanks for letting me know about this issue 👍
