### ISSUE TITLE
I can't connect! 

### ISSUE THREAD

**Issue by Cleanerx01** [andersevenrud/ha-nexa-bridge-x#50]
Using the right IP and nexa as username and password without success.

Nexa Bridge 3
2.5.8
![Screenshot_20241106_115335_io homeassistant companion android_edit_739633804458493](https://github.com/user-attachments/assets/7cbbfca0-6a7a-4be7-98bc-1c56fe9b2ce3)

**Comment by andersevenrud** [comment]
Have you checked the HA logs ? It might give some hints about what's going on here.

**Comment by Cleanerx01** [comment]
No I can't see anything in the logs.

I have tried to log in to my IP address through the browser using nexa as
username and password, but without success :-(

Den ons 6 nov. 2024 13:03Anders Evenrud ***@***.***> skrev:

**Comment by andersevenrud** [comment]
> I have tried to log in to my IP address through the browser using nexa as username and password, but without success :-(

Hm. According to Nexa all devices ship with `nexa / nexa` as username / password for all bridges, so that's a bit strange 🤔 

Did you get this device second hand or a returned item in a store ?

**Comment by andersevenrud** [comment]
I see that you have the firmware `2.5.8`, which is undocumented (from what I can see). I also went to their website and it seems that they now sell a "Bridge 3", which is black instead of white. I was not aware of this.

Maybe you have this newer device ?

**Comment by andersevenrud** [comment]
Aha. I personally do not have access to a Bridge 3 (or the firmware), so let's hope support comes through with some info 🤞

**Comment by andersevenrud** [comment]
Just a heads-up regarding this integration. Currently, there is a check to see if it is a "Bridge1" or "Bridge2" (aka "Bridge X") depending on the checkbox in the login form shown in HA.

So if your bridge identifies itself as "Bridge3" when the integration tries to connect you will get an error. If this is the case, 
could you provide me with a couple of samples of data from your bridge API ?

It is fairly simple to perform and some examples are provided in my [help documentation](https://github.com/andersevenrud/ha-nexa-bridge-x/blob/main/HELP.md#im-still-having-issues-help). I can assist if needed (either here or on discord, which is linked in the docs).

This will show if the firmware is fully compatible, and I can update the check to accept "Bridge3" and publish a new release of the integration.

**Comment by Cleanerx01** [comment]
Den ons 6 nov. 2024 21:56Anders Evenrud ***@***.***> skrev:

**Comment by Cleanerx01** [comment]
I'm pretty new to all this so I might be doing something wrong! Below is an
example, when I click on "open link" I never get there!






Den mån 11 nov. 2024 10:30JG Infotainment ***@***.***> skrev:

**Comment by andersevenrud** [comment]
The image from your email does not show up. Something must have gone wrong in sending.

**Comment by Cleanerx01** [comment]
Den mån 11 nov. 2024 14:44Anders Evenrud ***@***.***> skrev:

**Comment by andersevenrud** [comment]
> Something must have gone wrong in sending.

You probably need to go directly to the issue on Github and comment there instead of putting attachments into email responses.

**Comment by Cleanerx01** [comment]
Are you Swedish or Norwegian? Can I contact you via messenger or e-mail?

Den mån 11 nov. 2024 21:01Anders Evenrud ***@***.***> skrev:

**Comment by andersevenrud** [comment]
Norwegian :) You can contact me on gmail (same username as on github).

**Comment by andersevenrud** [comment]
Conclusion from discussion via email: Bridge3 firmware is basically same as Bridge2. Support has been added.
