### ISSUE TITLE
Does it detect newly added devices in Nexa Bridge X?

### ISSUE THREAD

**Issue by carestad** [andersevenrud/ha-nexa-bridge-x#51]
As title says, I am wondering if it should be able to pick up on when I add a new device to my Bridge X.  Usually I have to do this via their own app. And afterwords they don't seem to appear in Home Assistant, neither if I restart it or reload the Nexa integration. Just wondering if it _should_ be able to or not :sweat_smile:

**Comment by andersevenrud** [comment]
It should be able to pick up the device if added via the Nexa app/web interface.

The integration just grabs whatever devices that the bridge reports via an API. A restart would have cleared out any cache or whatever, so I'm not quite sure what the problem would be at this moment. 

Are you able to control/monitor the devices from there? Are these zwave? 

Can you see anything in the HA logs related to what you have added? Might wanna enable verbose logging for this. See the HELP file in repo for more info.

**Comment by andersevenrud** [comment]
Also, what firmware version? :)

**Comment by carestad** [comment]
> It should be able to pick up the device if added via the Nexa app/web interface.

Alright. They are all added via the app :) 

> The integration just grabs whatever devices that the bridge reports via an API. A restart would have cleared out any cache or whatever, so I'm not quite sure what the problem would be at this moment. 
> 
> Are you able to control/monitor the devices from there? Are these zwave? 

Not zwave I think. Just plain Nexa on/off switches (MYCR-1000) and a door bell (slap nexa but not sure of model right now).

> Can you see anything in the HA logs related to what you have added? Might wanna enable verbose logging for this. See the HELP file in repo for more info. 

Very quick look now and I see this error has been repeated a few times:

```
Logger: homeassistant.components.switch
Source: helpers/entity_platform.py:761
integration: Switch (documentation, issues)
First occurred: 22:34:37 (4 occurrences)
Last logged: 22:34:37

Platform nexa_bridge_x does not generate unique IDs. ID switch_Fel5IhPBsXHNzP2K already exists - ignoring switch.nexa_bridge_x_stuelampe_switch
Platform nexa_bridge_x does not generate unique IDs. ID switch_RLb6aj1fvwKJXGlx already exists - ignoring switch.nexa_bridge_x_test2_switch
Platform nexa_bridge_x does not generate unique IDs. ID switch_fPBhCZkmeGSmZTxm already exists - ignoring switch.nexa_bridge_x_test3_switch
Platform nexa_bridge_x does not generate unique IDs. ID switch_yQ4PbgE5KbHMpfyq already exists - ignoring switch.nexa_bridge_x_test1_switch
```

> Also, what firmware version? :) 

Not 100% sure where to find it, but in the app under `Settings > Show information` I see it has a version number: 2.4.1

**Comment by andersevenrud** [comment]
Are you able to control the devices from nexa app ?

I think I might need some information from your bridge API to help here. There are some instructions in the HELP file how to do this that you can take a look at. Would you be comfortable doing this ? I can assist if needed (both here, via email or on discord)

> I see it has a version number: 2.4.1

OK, great!

**Comment by andersevenrud** [comment]
Just had a little bit more time to look into this.

Your device should be supported according to a [user report](https://github.com/andersevenrud/ha-nexa-bridge-x/issues/6#issuecomment-1725006983). Also, according to your logs it was detected as a "switch".

> And afterwords they don't seem to appear in Home Assistant

I just had a though here. By "appearing", do you mean in some kind of Card on the dashboard, or from the list of HA Entities.

**Comment by carestad** [comment]
> Are you able to control the devices from nexa app ?

Yes, both nexa app and HA work fine to control the devices (the ones that appear in HA)

> I think I might need some information from your bridge API to help here. There are some instructions in the HELP file how to do this that you can take a look at. Would you be comfortable doing this ? I can assist if needed (both here, via email or on discord)

Sure!

> I just had a though here. By "appearing", do you mean in some kind of Card on the dashboard, or from the list of HA Entities.

Yes, sorry, I mean the list of devices is not quite in sync with the list of devices in the Nexa app / website. If I rename a device in the Nexa app, it does not rename in HA. If I add a new device in the Nexa app, it does not seem to get picked up in HA either.

**Comment by andersevenrud** [comment]
> Yes, sorry, I mean the list of devices is not quite in sync with the list of devices in the Nexa app / website. If I rename a device in the Nexa app, it does not rename in HA. If I add a new device in the Nexa app, it does not seem to get picked up in HA either.

I'm not sure what you mean by "list of devices" here (if it's a card or entities listings). Can you share a screenshot of where you expect things to happen ?

**Comment by Avsy** [comment]
test

**Comment by carestad** [comment]
> > Yes, sorry, I mean the list of devices is not quite in sync with the list of devices in the Nexa app / website. If I rename a device in the Nexa app, it does not rename in HA. If I add a new device in the Nexa app, it does not seem to get picked up in HA either.
> 
> I'm not sure what you mean by "list of devices" here (if it's a card or entities listings). Can you share a screenshot of where you expect things to happen ?

Ah, yes of course. Sorry for the confusion. With list of devices I generally mean under the Nexa Bridge X under System > Devices > Nexa Bridge X.

![image](https://github.com/user-attachments/assets/7a5f595e-a26f-4884-8bd3-8cfd26095621)

(and then if you click the `devices` link there - either one of them)

I added the debug statement to the `configuration.yaml` and restarted HA now and it seemed to have now picked up name changes for devices now :smile: Not sure if that is coincidental or not.

I also added a new device today and it was detected when restarting HA, so maybe I've just been unlucky?

**Comment by andersevenrud** [comment]
> I also added a new device today and it was detected when restarting HA, so maybe I've just been unlucky?

Try just reloading the integration next time. That should be enough and you won't get any downtime for any other integrations you have running.
